### ISSUE TITLE
Show fixed part of audio

### ISSUE THREAD

**Issue by larsrgit** [katspaugh/wavesurfer.ts#53]
Is it possible to set a fixed start and end time of the audio to show?

I tried the following
```
this.ws.setOptions({autoCenter: true})
this.ws.zoom( container.getClientWidth  / (end - start ) / 2 )
this.ws.setTime(start + (end-start)/2)
this.ws.setOptions({autoCenter: false})
```

Before the last line is executed, the wavesurfer shows as intended the part of the audio between start and end. But setting the autoCenter to false to prevent the view from changing during playback calls renderer.reRender() and resets the view to the start of the audio.

**Comment by katspaugh** [comment]
That’s a bug, re-render should keep the previous position when possible.

**Comment by katspaugh** [comment]
I've investigated a bit, and it's not exactly a bug, just the way `setTime` works. It sets the audio time immediately, but renders it only when the `timeupdate` event is emitted. Since browser events are asynchronous, your second `setOptions` happens before the rendering. So it never renders it with `autoCenter: true`, it gets changed to false too quickly.

To fix the issue, you should do the following:

```
this.ws.setOptions({
  minPxPerSec: container.getClientWidth  / (end - start ) / 2),
  autoCenter: true
})
this.ws.setTime(start + (end-start)/2)

// A small timeout so that it renders the new time position with autoCenter: true
setTimeout(() => {
  // No need to call setOptions here, because there's nothing to re-render, we just need to flip that flag
  this.ws.options.autoCenter = false
}, 100)
```

**Comment by katspaugh** [comment]
I could make `setTime` also render the progress immediately, but I feel like the situation with `autoCenter` specifically is just an edge case.

**Comment by katspaugh** [comment]
True! Glad it worked.
