### ISSUE TITLE
Custom progress Icon

### ISSUE THREAD

**Issue by matadantelinga** [katspaugh/wavesurfer.ts#65]
Hi, I wondering in this new version I can apply / override css styles on the timeline progress (not sure correct term for this, please check the image attached)
![Screen Shot 2023-05-08 at 14 49 03](https://user-images.githubusercontent.com/20659919/236767117-e36c3fe3-6b29-467d-968d-56a4aa00f85f.png)
In previous version I can put my css on styled.div but currently I cannot select the :host selector. Bytheway I work on react. I wonder how I can override the css rules for the timeline progress. Thanks

**Comment by katspaugh** [comment]
Good question. It's already the 3rd or 4th question/ request about styling different elements.

Version 6 and earlier could be customized directly via CSS because, but v7 alpha uses Shadow DOM to encapsulate its components.

I've just found out there's a way to still allow certain parts of Shadow DOM to be [styled](https://css-tricks.com/styling-in-the-shadow-dom-with-css-shadow-parts/). I'm going to add this `::part()` thing to wavesurfer elements, including the cursor (the vertical bar you're referring to).

**Comment by matadantelinga** [comment]
and for now, is there any other way to do that? while wait for the update

**Comment by katspaugh** [comment]
You could inject CSS into the container.
Something like
```js
const style = document.createElement('style');
style.type = 'text/css';
style.innerHTML = '.cssClass { color: #f00; }';
wavesurfer.getWrapper().appendChild(style)
```
